services:
  scd41_influx:
    image: stianjosok/scd41-influx:latest
    container_name: scd41-influx
    devices:
      - /dev/i2c-1:/dev/i2c-1
    environment:
      I2C_DEV: /dev/i2c-1          # change if sensor is on a different bus (e.g. /dev/i2c-0)
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INTERVAL_SEC: "10"            # seconds between readings (min: 5, sensor limitation)
      MEASUREMENT: "scd41"          # InfluxDB measurement name
      LOG_LEVEL: INFO               # DEBUG | INFO | WARNING | ERROR
      INFLUX_BATCH_SIZE: "6"        # number of points to buffer before writing to InfluxDB
      INFLUX_FLUSH_MS: "60000"      # max milliseconds before force flush
      # LOCATION: ""               # optional tag added to every data point e.g. livingRoom
    group_add:
      - "${I2C_GID:-994}"
    restart: unless-stopped
