services:
  scd41_influx:
    image: stianjosok/scd41-influx:latest
    container_name: scd41-influx
    devices:
      - /dev/i2c-1:/dev/i2c-1
    environment:
      I2C_DEV: /dev/i2c-1
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INTERVAL_SEC: "10"
      MEASUREMENT: "scd41"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    group_add:
      - "${I2C_GID:-994}"
    restart: unless-stopped
